channels:
  - conda-forge
  - defaults
dependencies:
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.0.5
  - attrs=21.4.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - beautifulsoup4=4.11.1
  - bleach=5.0.1
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2022.6.15
  - certifi=2022.6.15
  - cffi=1.15.0
  - charset-normalizer=2.0.12
  - colorama=0.4.5
  - cryptography=37.0.2
  - cycler=0.11.0
  - debugpy=1.6.0
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - executing=0.8.3
  - flit-core=3.7.1
  - fonttools=4.33.3
  - freetype=2.10.4
  - gettext=0.19.8.1
  - glib=2.70.2
  - glib-tools=2.70.2
  - gst-plugins-base=1.20.3
  - gstreamer=1.20.3
  - icu=70.1
  - idna=3.3
  - importlib-metadata=4.11.4
  - importlib_resources=5.8.0
  - intel-openmp=2022.1.0
  - ipykernel=6.15.0
  - ipython=8.4.0
  - ipython_genutils=0.2.0
  - jedi=0.18.1
  - jinja2=3.1.2
  - jpeg=9e
  - json5=0.9.5
  - jsonschema=4.6.1
  - jupyter_client=7.3.4
  - jupyter_core=4.10.0
  - jupyterlab=2.3.2
  - jupyterlab_pygments=0.2.2
  - jupyterlab_server=1.2.0
  - jupytext=1.13.8
  - kiwisolver=1.4.3
  - krb5=1.19.3
  - lcms2=2.12
  - lerc=3.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libclang=14.0.6
  - libclang13=14.0.6
  - libdeflate=1.12
  - libffi=3.4.2
  - libglib=2.70.2
  - libiconv=1.16
  - liblapack=3.9.0
  - libogg=1.3.4
  - libpng=1.6.37
  - libsodium=1.0.18
  - libtiff=4.4.0
  - libvorbis=1.3.7
  - libwebp=1.2.2
  - libwebp-base=1.2.2
  - libxcb=1.13
  - libzlib=1.2.12
  - lz4-c=1.9.3
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - markdown-it-py=2.1.0
  - markupsafe=2.1.1
  - matplotlib=3.5.2
  - matplotlib-base=3.5.2
  - matplotlib-inline=0.1.3
  - mdit-py-plugins=0.3.0
  - mdurl=0.1.0
  - mistune=0.8.4
  - mkl=2022.1.0
  - mpmath=1.2.1
  - msys2-conda-epoch=20160418
  - munkres=1.1.4
  - nbclient=0.6.4
  - nbconvert=6.5.0
  - nbconvert-core=6.5.0
  - nbconvert-pandoc=6.5.0
  - nbformat=5.4.0
  - nest-asyncio=1.5.5
  - notebook=6.4.12
  - numpy=1.22.4
  - openjpeg=2.4.0
  - openssl=1.1.1p
  - packaging=21.3
  - pandoc=2.18
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pcre=8.45
  - pickleshare=0.7.5
  - pillow=9.1.1
  - pip=22.1.2
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.30
  - psutil=5.9.1
  - pthread-stubs=0.4
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.12.0
  - pyopenssl=22.0.0
  - pyparsing=3.0.9
  - pyqt=5.15.4
  - pyqt5-sip=12.9.0
  - pyrsistent=0.18.1
  - pysocks=1.7.1
  - python=3.10.5
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.15.3
  - python_abi=3.10
  - pywin32=303
  - pywinpty=2.0.5
  - pyyaml=6.0
  - pyzmq=23.2.0
  - qt-main=5.15.4
  - requests=2.28.0
  - scipy=1.8.1
  - send2trash=1.8.0
  - setuptools=62.6.0
  - sip=6.5.1
  - six=1.16.0
  - soupsieve=2.3.1
  - sqlite=3.39.0
  - stack_data=0.3.0
  - sympy=1.10.1
  - tbb=2021.5.0
  - terminado=0.15.0
  - tinycss2=1.1.1
  - tk=8.6.12
  - toml=0.10.2
  - tornado=6.1
  - traitlets=5.3.0
  - typing_extensions=4.2.0
  - tzdata=2022a
  - ucrt=10.0.20348.0
  - unicodedata2=14.0.0
  - urllib3=1.26.9
  - vc=14.2
  - vs2015_runtime=14.29.30037
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.37.1
  - win_inet_pton=1.1.0
  - winpty=0.4.3
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.5
  - yaml=0.2.5
  - zeromq=4.3.4
  - zipp=3.8.0
  - zlib=1.2.12
  - zstd=1.5.2
